"""
Growth Playbook

A complete growth playbook for a platform at a given stage.
Generated by the cold start engine from category knowledge.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from .category import (
    AudienceArchetype,
    CategoryKnowledge,
    CategoryProfile,
    ChannelRecommendation,
)

logger = logging.getLogger(__name__)


@dataclass
class MessageTemplate:
    id: str
    stage: str
    channel: str
    subject: str
    body: str
    tone: str
    cta: str


@dataclass
class PolicySpec:
    name: str
    trigger_events: List[str]
    conditions: List[Dict[str, Any]]
    condition_logic: str
    action_type: str
    channel: Optional[str]
    priority: int
    payload_template: Dict[str, Any]
    delay_hours: float
    valid_hours: float
    cooldown_hours: float
    max_executions_per_identity: int
    abort_if_events: List[str]
    description: str = ""


@dataclass
class ActivationStep:
    day: int
    trigger: str
    condition: str
    action_type: str
    message_template: str
    abort_if: List[str]
    goal: str


@dataclass
class GrowthPlaybook:
    platform_id: str
    category: CategoryProfile
    generated_at: datetime
    stage: str
    target_archetypes: List[AudienceArchetype]
    primary_archetype: AudienceArchetype
    acquisition_channels: List[ChannelRecommendation]
    budget_split: Dict[str, float]
    estimated_cac: float
    activation_bottleneck: str
    first_value_moment: str
    activation_sequence: List[ActivationStep]
    value_proposition: str
    primary_messages: List[MessageTemplate]
    recommended_policies: List[PolicySpec]
    success_metrics: List[str]
    cold_start_window_days: int


_VALUE_PROPS: Dict[str, str] = {
    "b2b_marketplace": "Connect with vetted professionals and grow your business through trusted transactions",
    "b2c_marketplace": "Discover unique products and sellers in a trusted marketplace",
    "saas": "Streamline your workflow and boost productivity with powerful tools",
    "fintech_trading": "Trade smarter with advanced tools, low fees, and real-time market access",
    "fintech_payments": "Accept payments seamlessly and manage your cash flow effortlessly",
    "edtech": "Learn in-demand skills from top instructors at your own pace",
    "healthtech": "Achieve your health and wellness goals with personalized guidance",
    "ecommerce": "Shop the best products with fast delivery and easy returns",
    "social": "Connect, share, and grow your community",
    "developer_tools": "Build faster with powerful APIs and developer-friendly tools",
    "generic": "Solve your challenges with a platform built for results",
}


class PlaybookGenerator:

    def generate(
        self,
        platform_id: str,
        category_profile: CategoryProfile,
        knowledge: CategoryKnowledge,
        platform_name: str = "",
        regions: Optional[List[str]] = None,
    ) -> GrowthPlaybook:
        archetypes = knowledge.audience_archetypes[:3]
        primary = archetypes[0]

        channels = list(knowledge.acquisition_channels)

        budget_split = dict(knowledge.default_budget_split)

        cac_low, cac_high = knowledge.typical_cac_range
        estimated_cac = (cac_low + cac_high) / 2.0

        activation_sequence = self._build_activation_sequence(knowledge)
        messages = self._build_messages(knowledge, primary, platform_name)
        policies = self._build_policy_specs(knowledge, platform_id)

        return GrowthPlaybook(
            platform_id=platform_id,
            category=category_profile,
            generated_at=datetime.now(timezone.utc),
            stage="pre_launch",
            target_archetypes=archetypes,
            primary_archetype=primary,
            acquisition_channels=channels,
            budget_split=budget_split,
            estimated_cac=estimated_cac,
            activation_bottleneck=knowledge.activation_bottleneck,
            first_value_moment=knowledge.first_value_moment,
            activation_sequence=activation_sequence,
            value_proposition=_VALUE_PROPS.get(knowledge.category_id, _VALUE_PROPS["generic"]),
            primary_messages=messages,
            recommended_policies=policies,
            success_metrics=knowledge.primary_kpis,
            cold_start_window_days=knowledge.cold_start_window_days,
        )

    def _build_activation_sequence(self, knowledge: CategoryKnowledge) -> List[ActivationStep]:
        steps = [
            ActivationStep(
                day=0,
                trigger="USER_REGISTERED",
                condition="total_sessions == 0",
                action_type="SHOW_ONBOARDING",
                message_template="welcome",
                abort_if=[],
                goal="Show onboarding flow and guide to first value moment",
            ),
            ActivationStep(
                day=1,
                trigger="SESSION_STARTED",
                condition="total_sessions == 1",
                action_type="SEND_EMAIL",
                message_template="first_action_nudge",
                abort_if=[knowledge.activation_events[-1]] if knowledge.activation_events else [],
                goal=f"Guide user toward: {knowledge.activation_bottleneck}",
            ),
            ActivationStep(
                day=2,
                trigger="scheduled",
                condition="days_inactive >= 2 AND total_sessions == 1",
                action_type="SEND_EMAIL",
                message_template="come_back",
                abort_if=["SESSION_STARTED"],
                goal="Re-engage single-session users before they forget",
            ),
            ActivationStep(
                day=7,
                trigger="scheduled",
                condition="days_inactive >= 7 AND total_sessions < 3",
                action_type="SEND_EMAIL",
                message_template="social_proof",
                abort_if=["SESSION_STARTED"],
                goal="Reactivate dormant users with social proof",
            ),
        ]

        if "PAYMENT_COMPLETED" in knowledge.activation_events:
            steps.append(ActivationStep(
                day=0,
                trigger="PAYMENT_COMPLETED",
                condition="total_conversions == 1",
                action_type="SEND_EMAIL",
                message_template="first_win",
                abort_if=[],
                goal="Celebrate first transaction to reinforce value",
            ))
            steps.append(ActivationStep(
                day=2,
                trigger="PAYMENT_COMPLETED",
                condition="total_conversions == 1",
                action_type="SEND_EMAIL",
                message_template="refer_a_friend",
                abort_if=[],
                goal="Convert first-time buyers into referrers",
            ))

        if any(e in knowledge.activation_events for e in ["ORDER_COMPLETED", "PAYMENT_COMPLETED"]):
            steps.append(ActivationStep(
                day=1,
                trigger="ORDER_COMPLETED",
                condition="total_conversions >= 1 AND fraud_score < 0.3",
                action_type="REQUEST_REVIEW",
                message_template="review_request",
                abort_if=[],
                goal="Collect reviews from satisfied customers",
            ))

        if any(e in knowledge.activation_events for e in ["LESSON_COMPLETED", "SESSION_ENDED"]):
            steps.append(ActivationStep(
                day=3,
                trigger="scheduled",
                condition="total_sessions >= 3 AND days_inactive < 3",
                action_type="SHOW_RECOMMENDATION",
                message_template="keep_going",
                abort_if=[],
                goal="Encourage streak continuation",
            ))

        return steps

    def _build_messages(
        self,
        knowledge: CategoryKnowledge,
        archetype: AudienceArchetype,
        platform_name: str,
    ) -> List[MessageTemplate]:
        name = platform_name or "our platform"
        return [
            MessageTemplate(
                id="welcome",
                stage="onboarding",
                channel="email",
                subject=f"Welcome to {name}!",
                body=f"You're in! Here's how to get started and reach your first value moment: {knowledge.first_value_moment}.",
                tone=archetype.message_tone,
                cta="Get Started",
            ),
            MessageTemplate(
                id="first_action_nudge",
                stage="activation",
                channel="email",
                subject=f"One step away from {knowledge.first_value_moment}",
                body=f"Most users who {knowledge.activation_bottleneck} see results within 24 hours.",
                tone=archetype.message_tone,
                cta="Take Action",
            ),
            MessageTemplate(
                id="come_back",
                stage="reengagement",
                channel="email",
                subject=f"We saved your spot on {name}",
                body=f"You started something great. Come back and complete {knowledge.activation_bottleneck}.",
                tone=archetype.message_tone,
                cta="Continue",
            ),
            MessageTemplate(
                id="social_proof",
                stage="reengagement",
                channel="email",
                subject=f"See what others achieved on {name}",
                body=f"Thousands of users have already experienced {knowledge.first_value_moment}. Don't miss out.",
                tone=archetype.message_tone,
                cta="Join Them",
            ),
        ]

    def _build_policy_specs(
        self,
        knowledge: CategoryKnowledge,
        platform_id: str,
    ) -> List[PolicySpec]:
        policies: List[PolicySpec] = []

        policies.append(PolicySpec(
            name="Welcome & Profile Completion",
            trigger_events=["USER_REGISTERED"],
            conditions=[{"field": "total_sessions", "operator": "lte", "value": 1}],
            condition_logic="AND",
            action_type="SHOW_ONBOARDING",
            channel=None,
            priority=90,
            payload_template={"template": "welcome", "flow": "onboarding"},
            delay_hours=0.0,
            valid_hours=24.0,
            cooldown_hours=0.0,
            max_executions_per_identity=1,
            abort_if_events=[],
            description="Show onboarding to new users immediately after registration",
        ))

        policies.append(PolicySpec(
            name="First Action Nudge",
            trigger_events=["SESSION_STARTED"],
            conditions=[
                {"field": "total_sessions", "operator": "lte", "value": 2},
                {"field": "total_conversions", "operator": "eq", "value": 0},
            ],
            condition_logic="AND",
            action_type="SEND_EMAIL",
            channel="email",
            priority=85,
            payload_template={"template": "first_action_nudge"},
            delay_hours=0.0,
            valid_hours=48.0,
            cooldown_hours=24.0,
            max_executions_per_identity=1,
            abort_if_events=knowledge.activation_events[-1:] if knowledge.activation_events else [],
            description=f"Nudge new users toward: {knowledge.activation_bottleneck}",
        ))

        policies.append(PolicySpec(
            name="48h No Return Re-engagement",
            trigger_events=[],
            conditions=[
                {"field": "days_inactive", "operator": "gte", "value": 2.0},
                {"field": "total_sessions", "operator": "lte", "value": 1},
            ],
            condition_logic="AND",
            action_type="SEND_EMAIL",
            channel="email",
            priority=80,
            payload_template={"template": "come_back"},
            delay_hours=0.0,
            valid_hours=48.0,
            cooldown_hours=72.0,
            max_executions_per_identity=2,
            abort_if_events=["SESSION_STARTED"],
            description="Re-engage users who haven't returned after 48 hours",
        ))

        policies.append(PolicySpec(
            name="7 Day Cold Reactivation",
            trigger_events=[],
            conditions=[
                {"field": "days_inactive", "operator": "gte", "value": 7.0},
                {"field": "total_sessions", "operator": "lt", "value": 3},
            ],
            condition_logic="AND",
            action_type="SEND_EMAIL",
            channel="email",
            priority=70,
            payload_template={"template": "social_proof"},
            delay_hours=0.0,
            valid_hours=72.0,
            cooldown_hours=168.0,
            max_executions_per_identity=2,
            abort_if_events=["SESSION_STARTED"],
            description="Reactivate dormant users with social proof after 7 days",
        ))

        if "PAYMENT_COMPLETED" in knowledge.activation_events:
            policies.append(PolicySpec(
                name="First Transaction Celebration",
                trigger_events=["PAYMENT_COMPLETED"],
                conditions=[{"field": "total_conversions", "operator": "eq", "value": 1}],
                condition_logic="AND",
                action_type="SEND_EMAIL",
                channel="email",
                priority=75,
                payload_template={"template": "first_win"},
                delay_hours=0.0,
                valid_hours=24.0,
                cooldown_hours=0.0,
                max_executions_per_identity=1,
                abort_if_events=[],
                description="Celebrate the user's first conversion",
            ))

            policies.append(PolicySpec(
                name="Post-First-Win Referral Ask",
                trigger_events=["PAYMENT_COMPLETED"],
                conditions=[{"field": "total_conversions", "operator": "eq", "value": 1}],
                condition_logic="AND",
                action_type="SEND_EMAIL",
                channel="email",
                priority=50,
                payload_template={"template": "refer_a_friend"},
                delay_hours=48.0,
                valid_hours=72.0,
                cooldown_hours=336.0,
                max_executions_per_identity=1,
                abort_if_events=[],
                description="Ask first-time converters to refer friends",
            ))

        if any(e in knowledge.activation_events for e in ["ORDER_COMPLETED", "PAYMENT_COMPLETED"]):
            policies.append(PolicySpec(
                name="Review Request",
                trigger_events=["ORDER_COMPLETED", "PAYMENT_COMPLETED"],
                conditions=[
                    {"field": "total_conversions", "operator": "gte", "value": 1},
                    {"field": "fraud_score", "operator": "lt", "value": 0.3},
                ],
                condition_logic="AND",
                action_type="REQUEST_REVIEW",
                channel=None,
                priority=40,
                payload_template={"template": "review_request"},
                delay_hours=24.0,
                valid_hours=72.0,
                cooldown_hours=168.0,
                max_executions_per_identity=3,
                abort_if_events=[],
                description="Request reviews from satisfied customers",
            ))

        policies.append(PolicySpec(
            name="Active User Upsell",
            trigger_events=[],
            conditions=[
                {"field": "total_sessions", "operator": "gte", "value": 5},
                {"field": "churn_score", "operator": "lt", "value": 0.3},
                {"field": "upsell_score", "operator": "gte", "value": 0.4},
            ],
            condition_logic="AND",
            action_type="SHOW_UPSELL",
            channel=None,
            priority=60,
            payload_template={"template": "upsell_active_user"},
            delay_hours=0.0,
            valid_hours=48.0,
            cooldown_hours=168.0,
            max_executions_per_identity=0,
            abort_if_events=[],
            description="Show upsell to engaged, low-churn users",
        ))

        return policies
